[package]
name = "simd-demo"
version = "0.1.0"
authors = ["blackanger <blackanger.z@gmail.com>"]
edition = "2018"

[dependencies]
jetscii = "0.4.3"
stdsimd = "0.1.0"
// faster = "0.5.0"

[[bin]]
path = "src/faster_main.rs"
name = "faster"

[[bin]]
path = "src/main.rs"
name = "main"